site_name: Maxwel Silva
site_url: https://maxwelmms.github.io/maxwelmms.github.io/
repo_url: https://github.com/maxwelmms/maxwelmms.github.io
nav:
  - Home: 'index.md'
  - Ansible: 'ansible.md'
  - Containers : 'containers.md'
  - Docker: 'docker.md'
  - Vagrant: 'vagrant.md'
  - SLES: 'sles.md'
  - RHEL: 'rhel.md'
  - 'IBM Power Systems':
    - 'AIX': 'ibm_power_systems_aix.md'
    - 'LPAR': 'ibm_power_systems_lpar.md'
    - 'Hardware': 'ibm_power_systems_hardware.md'
    - 'IBM Support': 'ibm_power_systems_ibmsuppt.md'
    - 'PowerVM (VIOS)': 'ibm_power_systems_powervm.md'
    - 'PowerHA': 'ibm_power_systems_powerha.md'
    - 'PowerVC': 'ibm_power_systems_powervc.md'
    - 'Performance and Management': 'ibm_power_systems_perfmgm.md'
    - 'HMC': 'ibm_power_systems_hmc.md'
  - OpenStack: 'openstack.md'
  - OpenShift: 'openshift.md'
  - Oracle: 'oracle.md'
  - Storage: 'storage.md'
  - Network: 'network.md'
  - Security: 'security.md'
markdown_extensions:
  - toc:
    permalink: "#"
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - admonition
  - sane_lists
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences
  - pymdownx.keys
docs_dir: src
edit_uri: edit/main/src/
site_dir: docs
